### ISSUE TITLE
connect.ini is clear text

### ISSUE THREAD

**Issue by matthiaz** [degausserx/Peltech#1]
This is probably a learning project, but the guy that thought it was a good idea to have something like connect.ini didn't really think things through.
Yes, you can fix your webserver in such a way that it will never be visible to the user. But I'd recommend using an extension that isn't shown by default (e.g.: a .php file ;-) )

**Comment by degausserx** [comment]
Nah this will have been me. This was a project from a beginners course a couple years ago, and we had a limited time to write our projects (2 weeks) so many things will be overlooked.. not to mention it was all done from scratch. Everyone else simply had a few pages named index.php, register.php, etc...

I did what I could in the time that I had ;x

**Comment by matthiaz** [comment]
clear ;-)
